server:
  port: 8088

spring:
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/pymerp_minimarket}
    username: ${DB_USER:pymerp}
    password: ${DB_PASSWORD:pymerp}
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
  flyway:
    enabled: true
    locations: classpath:db/migration

logging:
  level:
    org.hibernate.SQL: INFO

security:
  jwt:
    secret: "ZGV2X3B5bWVyX21pbmltYXJrZXRfc2VjcmV0XzMyX2J5dGVzX2xvbmc="
    expiration-minutes: 720

app:
  cors:
    allowed-origins: ${CORS_ALLOWED_ORIGINS:http://localhost:5176,http://localhost:5173}

seed:
  enabled: true
